import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

test('main page exposes agent console shell and module import', () => {
  const html = readFileSync(resolve('public/index.html'), 'utf8');
  const js = readFileSync(resolve('public/client.js'), 'utf8');
  const agentConsole = readFileSync(resolve('public/agent-console.js'), 'utf8');
  const css = readFileSync(resolve('public/styles.css'), 'utf8');

  assert.match(html, /id="agentBtn"/);
  assert.match(html, /id="homeAgentBtn"/);
  assert.match(html, /id="mbarAgentBtn"/);
  assert.match(html, /id="agentSheet"/);
  assert.match(html, /id="agentTaskForm"/);
  assert.match(html, /id="agentModel"/);
  assert.match(html, /id="agentProjectPath"/);
  assert.match(html, /id="agentTaskList"/);
  assert.match(html, /id="agentApprovalList"/);
  assert.match(html, /id="agentOutput"/);
  assert.match(html, /id="agentInputForm"/);
  assert.match(html, /id="agentInput"/);
  assert.match(html, /id="agentDelivery"/);
  assert.match(js, /import \{ initAgentConsole \} from '\.\/agent-console\.js';/);
  assert.match(js, /initAgentConsole\(/);
  assert.match(agentConsole, /querySelectorAll\('\[data-agent-open\]'\)/);
  assert.match(agentConsole, /data-task-action/);
  assert.match(agentConsole, /api\.cancelTask\(/);
  assert.match(agentConsole, /toast\(error\.message,\s*'err'\)/);
  assert.match(agentConsole, /model:\s*modelInput\.value\.trim\(\)/);
  assert.match(agentConsole, /projectPath:\s*projectPathInput\.value\.trim\(\)/);
  assert.match(css, /\.agent-sheet/);
  assert.match(css, /\.agent-task-action/);
  assert.match(css, /\.agent-entry-btn/);
  assert.match(css, /\.mkey--agent/);
  assert.match(css, /\.agent-output\s*\{[^}]*overflow-y:\s*auto/s);
  assert.match(css, /\.agent-output\s*\{[^}]*-webkit-overflow-scrolling:\s*touch/s);
  assert.match(css, /\.agent-output\s*\{[^}]*overscroll-behavior:\s*contain/s);
  assert.match(css, /\.agent-output-tail\s*\{[^}]*overflow:\s*visible/s);
});
