services:
  - type: web
    name: tiny-connect
    runtime: docker
    plan: free
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DIRECT_LINK
        sync: false
